name: gans_what
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - numpy==2.1.2
      - pillow==11.0.0
      - scipy==1.15.3
      - tqdm==4.66.5
      - click==8.2.1
      - requests==2.32.4
      - python-dotenv==1.1.1
