name: gans_what
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - numpy=2.1.2
  - pillow=11.0.0
  - scipy=1.15.3
  - matplotlib=3.9.2
  - tqdm=4.66.5
  - click=8.2.1
  - requests=2.32.4
  - python-dotenv=1.1.1
